// Re-export everything for backwards compatibility
export { db, db as database } from './schema';

// Entities
export {
  getAllEntities,
  getEntitiesByType,
  getEntity,
  createEntity,
  updateEntity,
  deleteEntity,
  getAllRelationships,
  getRelationshipsForEntity,
  createRelationship,
  deleteRelationship,
  getFamilyTreeData,
  getPersonality,
  savePersonality,
  getAllPersonalities,
  addMedia,
  getMediaForEntity,
  getMediaForEvent,
  deleteMedia,
  getArcPointsForEntity,
  addArcPoint,
  updateArcPoint,
  deleteArcPoint,
  getArcDimensions,
  addArcDimension,
  updateArcDimension,
  deleteArcDimension,
  getArcClosure,
  saveArcClosure,
  getAllArcTypes,
  createArcType,
  deleteArcType,
  logLoreChange,
  getLoreHistory,
  getAllLoreHistory,
  calculateAge,
} from './entities';

// Events
export {
  getAllEvents,
  getEvent,
  createEvent,
  updateEvent,
  deleteEvent,
  getEventParticipants,
  addEventParticipant,
  removeEventParticipant,
  getEventsForEntity,
  getEventCausality,
  addEventCausality,
  updateEventCausality,
  removeEventCausality,
  getCausesForEvent,
  getEffectsOfEvent,
  getPlotlines,
  addPlotline,
  updatePlotline,
  deletePlotline,
  getLocationPositions,
  setLocationPosition,
  getAllTravelDistances,
  getTravelDistance,
  setTravelDistance,
  deleteTravelDistance,
  validateTravelTime,
} from './events';

// Writing
export {
  getAllChapters,
  getChapter,
  createChapter,
  updateChapter,
  deleteChapter,
  getScenesForChapter,
  getAllScenes,
  getScene,
  createScene,
  updateScene,
  deleteScene,
  getSceneCharacters,
  addSceneCharacter,
  removeSceneCharacter,
  getSceneDrafts,
  saveSceneDraft,
  deleteSceneDraft,
  getAllDialogues,
  getDialoguesForScene,
  createDialogue,
  updateDialogue,
  deleteDialogue,
  getAllWritingGoals,
  createWritingGoal,
  updateWritingGoal,
  deleteWritingGoal,
  getWritingSessions,
  logWritingSession,
  getTotalWordCount,
  compileManuscript,
  getChronologicalOrder,
  getReadingOrder,
  getAllPlotBeats,
  createPlotBeat,
  updatePlotBeat,
  deletePlotBeat,
  reorderPlotBeats,
  getAllFrames,
  createFrame,
  updateFrame,
  deleteFrame,
  getAllPoems,
  createPoem,
  updatePoem,
  deletePoem,
  getAllThemes,
  createTheme,
  updateTheme,
  deleteTheme,
  getThemeOccurrences,
  addThemeOccurrence,
  removeThemeOccurrence,
} from './writing';

// Knowledge
export {
  getAllFacts,
  createFact,
  updateFact,
  deleteFact,
  getKnowledgeForEntity,
  getKnowledgeForFact,
  addKnowledge,
  removeKnowledge,
  getReaderKnowledgeAtScene,
  getAllSetups,
  createSetup,
  updateSetup,
  deleteSetup,
  getUnresolvedSetups,
  getAllRules,
  getRulesBySystem,
  createRule,
  updateRule,
  deleteRule,
  getTruthLayersForFact,
  addTruthLayer,
  removeTruthLayer,
  getAllNamingRules,
  getNamingRulesByCulture,
  createNamingRule,
  updateNamingRule,
  deleteNamingRule,
} from './knowledge';

// World
export {
  getAllCreatures,
  getCreature,
  createCreature,
  updateCreature,
  deleteCreature,
  getAllLanguages,
  getLanguage,
  createLanguage,
  updateLanguage,
  deleteLanguage,
  getVocabulary,
  addWord,
  updateWord,
  deleteWord,
  getAllCurrencies,
  createCurrency,
  updateCurrency,
  deleteCurrency,
  getCalendar,
  createCalendar,
  updateCalendar,
  getDialogueNodes,
  getDialogueNode,
  createDialogueNode,
  updateDialogueNode,
  deleteDialogueNode,
  getDialogueChoices,
  createDialogueChoice,
  updateDialogueChoice,
  deleteDialogueChoice,
} from './world';

// Project
export {
  getProjectSettings,
  updateProjectSettings,
  setCustomMap,
  getAllProjects,
  getActiveProject,
  createProject,
  updateProject,
  deleteProject,
  switchProject,
  exportFullBackup,
  importFullBackup,
  clearAllData,
} from './project';

// Analysis
export {
  searchLore,
  findScenesWithCharacters,
  checkContinuity,
  analyzePacing,
  analyzeWordFrequency,
  getCharacterAgeAtEvent,
} from './analysis';

// Quests
export {
  getAllQuests,
  getQuest,
  createQuest,
  updateQuest,
  deleteQuest,
  getQuestObjectives,
  createQuestObjective,
  updateQuestObjective,
  deleteQuestObjective,
  getQuestRewards,
  createQuestReward,
  updateQuestReward,
  deleteQuestReward,
  getQuestPrerequisites,
  createQuestPrerequisite,
  deleteQuestPrerequisite,
  getQuestStages,
  createQuestStage,
  updateQuestStage,
  deleteQuestStage,
  getQuestBranches,
  getQuestBranchesFrom,
  getQuestBranchesTo,
  createQuestBranch,
  updateQuestBranch,
  deleteQuestBranch,
  getQuestChains,
  getQuestStats,
} from './quests';
